[build]
publish = "public"
command = "hugo version && hugo config && hugo --gc --minify -d public/docs;"

[context.production.environment]
HUGO_VERSION = "0.139.0"
HUGO_PARAMS_TESTENV="Netlify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.139.0"
HUGO_PARAMS_TESTENV="Netlify"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"

[plugins.inputs]
debug = true

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*"

[headers.values]
Content-Security-Policy = """
  default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;
  worker-src * blob: data:;
  script-src * 'unsafe-inline' 'unsafe-eval';
  connect-src 'self' https://*.sitebay.org https://*.algolia.net;
  connect-src *;
  frame-ancestors *;
"""

[[redirects]]
from = "/docs/blog/*"
to = "/docs/sections/"
status = 200

[[redirects]]
from = "/docs/marketplace/*"
to = "/docs/sections/"
status = 200

[[redirects]]
from = "/docs/resources/*"
to = "/docs/sections/"
status = 200

[[redirects]]
from = "/docs/*"
to = "/docs/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/docs/"
